package io.github.yuroyami.libmpvkt.buildtools

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/** Writes BuildInfo.kt from the pins in buildscripts/include/depinfo.sh, so code and docs cannot disagree about what is inside. */
abstract class GenerateBuildInfoTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val depinfo: RegularFileProperty

    @get:Input
    abstract val libraryVersion: Property<String>

    @get:Input
    abstract val minSdk: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pins = parsePins(depinfo.get().asFile.readText())
        val file = outputDir.get().asFile.resolve("io/github/yuroyami/libmpvkt/BuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(render(pins, libraryVersion.get(), minSdk.get()))
    }

    companion object {
        private val pinLine = Regex("""^v_([a-z0-9_]+)=(\S+)$""", RegexOption.MULTILINE)

        /** Every `v_<name>=<value>` line of depinfo.sh, keyed by name. */
        fun parsePins(text: String): Map<String, String> =
            pinLine.findAll(text).associate { it.groupValues[1] to it.groupValues[2] }

        /** The Kotlin source of BuildInfo. Throws [IllegalStateException] naming any pin that is absent. */
        fun render(pins: Map<String, String>, version: String, minSdk: Int): String {
            fun pin(key: String): String = pins[key] ?: error("depinfo.sh has no v_$key")
            return """
                |// Generated by GenerateBuildInfoTask from buildscripts/include/depinfo.sh. Do not edit.
                |package io.github.yuroyami.libmpvkt
                |
                |/**
                | * What this build of libmpvKt contains. Readable before [MPVLib.create]. Once the core is
                | * initialised, mpv reports the same through its `mpv-version` and `ffmpeg-version` properties.
                | */
                |public object BuildInfo {
                |    /** The libmpvKt artifact version. */
                |    public const val LIBMPVKT: String = "$version"
                |    /** The mpv release, without the leading v. */
                |    public const val MPV: String = "${pin("mpv")}"
                |    /** The FFmpeg release, without the leading n. */
                |    public const val FFMPEG: String = "${pin("ffmpeg")}"
                |    public const val LIBASS: String = "${pin("libass")}"
                |    public const val LIBPLACEBO: String = "${pin("libplacebo")}"
                |    public const val DAV1D: String = "${pin("dav1d")}"
                |    public const val MBEDTLS: String = "${pin("mbedtls")}"
                |    public const val HARFBUZZ: String = "${pin("harfbuzz")}"
                |    public const val FREETYPE: String = "${pin("freetype")}"
                |    public const val FRIBIDI: String = "${pin("fribidi")}"
                |    public const val LIBUNIBREAK: String = "${pin("unibreak")}"
                |    public const val LUA: String = "${pin("lua")}"
                |    /** The Android NDK the libraries were compiled with. */
                |    public const val NDK: String = "${pin("ndk")}"
                |    /** The lowest Android API level the libraries were compiled for. */
                |    public const val MIN_SDK: Int = $minSdk
                |    /** The ABIs the AAR carries. */
                |    public val ABIS: List<String> = listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64")
                |}
                |""".trimMargin()
        }
    }
}
