<#--
  Kite: Dokka footer override. Same structure as the 2.2.0 default, with the
  "Generated by Dokka" credit demoted below the project's own footer message.
-->
<#macro display>
    <div class="footer">
        <div class="footer--container">
            <a href="#content" id="go-to-top-link" class="footer--button footer--button_go-to-top"></a>
            <div class="footer--content">
                <div>
                    <div>${footerMessage}</div>
                    <span>Generated by </span>
                    <a class="footer--link footer--link_external" href="https://github.com/Kotlin/dokka">
                        Dokka
                    </a>
                </div>
            </div>
        </div>
    </div>
</#macro>
